services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app/main.py
  
  init_scraper:
    image: curlimages/curl
    depends_on:
      - api
    entrypoint: >
      sh -c "sleep 10 && curl -X POST http://api:5000/init"
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: celery -A app.tasks worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    volumes:
      - ./backend:/app
    working_dir: /app

  redis:
    image: redis:alpine

  chatbot-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    volumes:
      - ./frontend/chatbot-ui:/chatbot-ui
