services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app/main.py
  
  init_scraper:
    image: curlimages/curl
    depends_on:
      - api
    entrypoint: >
      sh -c "sleep 10 && curl -X POST http://api:5000/init"
  
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./backend:/app
    working_dir: /app

  redis:
    image: redis:alpine

  chatbot-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    volumes:
      - ./frontend/chatbot-ui:/chatbot-ui

  n8n:
    build:
      context: ./workflows
      dockerfile: Dockerfile
    ports:
      - 5678:5678
    depends_on:
      - api
    volumes:
      - ./workflows/n8n_data:/home/node/.n8n
    env_file:
      - ./workflows/.env
    entrypoint: >
      sh -c "n8n import:credentials --input=/data/n8n_credentials.json &&
             n8n import:workflow --input=/data/n8n_workflow.json &&
             n8n start"

